### ISSUE TITLE
awkward to construct `Event` in 3.0.0

### ISSUE THREAD

**Issue by dimbleby** [smol-rs/polling#148]
we have some constructors eg
```rust
 impl Event {
      /// All kinds of events (readable and writable).
      ///
      /// Equivalent to: `Event { key, readable: true, writable: true }`
      pub const fn all(key: usize) -> Event {
          ...
```
but the claimed equivalence is not true: the addition of the private `extra` field makes it impossible to construct an `Event` that way.

So code that in polling 2.x goes like:
```
  let readable = am_i_interested_in_reads();
  let writable = am_i_interested_in_writes();
  let event = Event { key, readable, writable };
```
has become awkward to write in polling 3.0.0

can we get an `Event::new(key, readable, writable)` to recover this?  or failing that I guess treat this as a bug report against the no-longer-true docs.

**Comment by notgull** [comment]
Thanks for the catch! I would accept a PR to add the new constructor as well as to fix the docs
