### ISSUE TITLE
can AsRawSource support unsafe fn source(&self)  

### ISSUE THREAD

**Issue by sxci** [smol-rs/polling#150]
add a trait function source(&self) -> AsSource in AsRawSource:
for #[cfg(unix)]:
    unsafe fn source(&self) -> BorrowedFd<'_> {
        BorrowedFd::borrow_raw(self.raw())
    }
#[cfg(windows)]:
    unsafe fn source(&self) -> BorrowedFd<'_> {
        BorrowedSocket::borrow_raw(self.raw())
    }

**Comment by notgull** [comment]
I'm sorry, I don't see why this would be useful. Can you elaborate further?

**Comment by sxci** [comment]
just like some function can use like:
```
    #[inline]
    pub(crate) fn delete(&self, poller: &Poller) -> Result<()> {
        // SAFETY: self.raw is a valid file descriptor
        let fd = unsafe { self.raw.as_source() };
        poller.delete(fd);
    }
```
then this kind function may move to `https://github.com/smol-rs/async-io/blob/master/src/reactor.rs` , this time, it is in  `https://github.com/smol-rs/async-io/blob/master/src/reactor/unix.rs`

but i am not sure.

**Comment by notgull** [comment]
This seems like a lot of extra complexity for little benefit. For the most part it's no different from just calling `borrow_raw`.

**Comment by sxci** [comment]
yes, it's `BorrowedFd::borrow_raw` or `BorrowedSocket::borrow_raw`.  just don't need cfg attribute in some case.
