### ISSUE TITLE
Poller::add has platform-specific behavior when trying to insert the same file descriptor multiple times

### ISSUE THREAD

**Issue by elinorbgr** [smol-rs/polling#151]
I encountered this when writing [this test](https://github.com/Smithay/calloop/blob/6a67e67fbc22a178b30ceea40f41f21ff73c920f/src/sources/generic.rs#L429-L473) for calloop.

I believe this is just the expression of the semantics of the underlying polling systems:
- epoll on Linux returns an error if we try to add the same FD multiple times (fails with `EEXIST`)
- kqueue on FreeBSD/macOS does not fail and returns a success on the same case (I don't know what it actually does though)

Not sure what would be best to do about it, but I believe it's worth at least documenting it.

**Comment by tobhe** [comment]
I've been tracking down Niri crashes on OpenBSD and it looks like they might be related to the changes introduced here. What seems to happen is that the sources tracking accumulates FDs that never get deleted. At some point the FD gets reused and inserting it fails with an AlreadyExists error.

As I understand the [manual](https://man.openbsd.org/kqueue.2) it should not be possible to have duplicate events in OpenBSD and a fd close implicitly removes the event from the queue which is not true for the sources list.
I'm still trying to figure out what the right solution here would be.
