### ISSUE TITLE
Add support for PS Vita

### ISSUE THREAD

**Issue by notgull** [smol-rs/polling#160]
Related: https://github.com/tokio-rs/mio/pull/1721

This will probably need to be tacked onto the `poll()` backend like ESP-IDF is.

**Comment by nikarh** [comment]
Hi, I will be glad to help with this target, although this will require porting rustix first

**Comment by sunfishcode** [comment]
rustix 0.38.20 now compiles under armv7-sony-vita-newlibeabihf.

**Comment by notgull** [comment]
@nikarh You said you wanted to help for this target; any updates on this?

**Comment by nikarh** [comment]
> @nikarh You said you wanted to help for this target; any updates on this?

Hi, sorry for the delay. I haven't started working on it yet.
I'm vacating till Christmas, but after that, I'll have some free time and do it.

**Comment by mamaicode** [comment]
Will attempt this one

**Comment by mamaicode** [comment]
@nikarh Thank you for pointing it out before I got started!
Which decision do we go with? keep me posted

**Comment by notgull** [comment]
> On Vita message written to pipe is not immediately available for `read` after calling `write` on the other side of the pipe.

Could this be solved by blocking on the `read` instead of using `NONBLOCK`?

**Comment by nikarh** [comment]
> > On Vita message written to pipe is not immediately available for `read` after calling `write` on the other side of the pipe.
> 
> Could this be solved by blocking on the `read` instead of using `NONBLOCK`?

Yes, I made a PR with just that. With this PR all tests actually pass on Vita (except for `many_connections` due to severely limited max fd count on the platform, but changing 100 to something like 60 makes it pass)

@mamaicode Sorry for stealing this from you 🙏 I had this code stashed locally on my machine and wasn't sure about making a PR since the solution is kinda ugly.
