### ISSUE TITLE
Smaller Events representation

### ISSUE THREAD

**Issue by Plecra** [smol-rs/polling#19]
With the array support that was recently added, smol could safely use a `Box<[platform::event; 1024]>` for the `Events` implementation. It'd bring the MSRV up to 1.47 though, which I'm guessing isn't ideal. Does the crate have an MSRV policy?

**Comment by stjepang** [comment]
It is set to 1.40.0 currently: https://github.com/stjepang/polling/blob/master/.github/workflows/build-and-test.yaml#L16
