### ISSUE TITLE
unsafe add: will it go back to safe?

### ISSUE THREAD

**Issue by keepsimple1** [smol-rs/polling#191]
https://github.com/smol-rs/polling/blob/77b4ed115674f9e7a6f8636cf5e9487a9cb06687/src/lib.rs#L510

Although this seems to have happened almost 6 months ago, it's sad that this API changed to be "unsafe". One of my project relies on this API heavily and we cannot upgrade to the latest "polling" due to this unsafe API. 

Is there any plan to make this safe again? ("polling" is a great library, I love using it).

**Comment by zeenix** [comment]
`unsafe` only means it's **potentially** unsafe and shouldn't stop you from using the library in any way. We can lie that it's safe by not declaring it so but all that will do is give you a false sense of safety.

**Comment by zeenix** [comment]
> `unsafe` only means it's **potentially** unsafe and shouldn't stop you from using the library in any way. We can lie that it's safe by not declaring it so but all that will do is give you a false sense of safety.

Having said that, looking at the [PR that changed it](https://github.com/smol-rs/polling/pull/123), I'm not sure why this method wasn't just changed to take `BorrowedFd` instead. @notgull ?

**Comment by notgull** [comment]
Since the poller uses the reference to the source without considering its lifetime it's essentially taking a raw pointer. I updated the signature to make this clear.

**Comment by zeenix** [comment]
> Since the poller uses the reference to the source without considering its lifetime it's essentially taking a raw pointer. I updated the signature to make this clear.

Thanks for explaining, @notgull. I'm closing this then.

**Comment by keepsimple1** [comment]
That's really fast to close an issue. It will be good to give the user a chance to follow up before closing ;-)

https://github.com/smol-rs/polling/blob/77b4ed115674f9e7a6f8636cf5e9487a9cb06687/src/lib.rs#L615 

I'm wondering, why is `modify()` able to take `AsSource`, not `AsRawSource`?

**Comment by notgull** [comment]
It is able to take a borrowed pointer because it's not kept around.
