### ISSUE TITLE
Odd documentation entry for `Event::is_err()`

### ISSUE THREAD

**Issue by pfumagalli** [smol-rs/polling#203]
In the docs for `Event::is_err()` 

https://github.com/smol-rs/polling/blob/cf2d60efca623ded6c94ca2f07495a367b0d7e01/src/lib.rs#L413-L414

it is stated:

> Returns `Some(true)` if the connection has failed, `Some(false)` if there is an error,
> or `None` if the platform does not support detecting this condition.

I assume it should say 

> _[...]_ `Some(false)` if there is _**no**_ error, _[...]_

In the various implementations I can see that the check is normally

```rs
Some(self.flags.contains(epoll::EventFlags::ERR))
```

So I assume my understanding is correct?

**Comment by notgull** [comment]
I would accept a PR to fix this.

**Comment by pfumagalli** [comment]
You got it, #204 

Thanks!
