### ISSUE TITLE
Removing the wepoll dependency?

### ISSUE THREAD

**Issue by Plecra** [smol-rs/polling#22]
Would it be possible to implement the windows backend directly in rust? I think making the code as accessible as possible to users is especially important with a library like this (mostly for debugging).

It looks like `mio` is written with `{nt, win}api`, and maybe it could be used as reference here.

**Comment by stjepang** [comment]
It would require a lot of effort and would likely introduce bugs in the beginning. The `wepoll` implementation in C is really high quality so I find little reason to port the code to Rust. It's true that porting would make compiling `polling` on windows a bit smoother though!

Anyways... I don't have the time to do this right now :( If somebody else wants to give this a shot, that would be very much appreciated!

**Comment by YorickPeterse** [comment]
mio ended up adopting the wepoll approach, but IIRC their code is written from scratch. Last I checked, there were still a bunch of issues with their implementation. This is why I avoid mio myself: its Windows support seems questionable at best. wepoll on the other hand is solid as a rock, and compiling it is quite easy/fast.

**Comment by notgull** [comment]
`wepoll` is fine for now. If we want to further integrate files into our event loop we'll probably either need to patch `wepoll` or come up with our own solution.
