### ISSUE TITLE
Use of non-existent BorrowFd::new() introduced with 2.3.0

### ISSUE THREAD

**Issue by nospam3089** [smol-rs/polling#42]
All attempts to build version 2.3.0 on illumos fails with the following error:

```
error[E0599]: no function or associated item named `new` found for struct `BorrowedFd` in the current scope
   --> src/port.rs:159:30
    |
159 |         unsafe { BorrowedFd::new(self.port_fd) }
    |                              ^^^ function or associated item not found in `BorrowedFd<'_>`

For more information about this error, try `rustc --explain E0599`.
error: could not compile `polling` due to previous error
```

It appears `src/port.rs` is only included for target_os = "illumos" || "solaris", but [BorrowedFd](https://doc.rust-lang.org/stable/std/os/unix/io/struct.BorrowedFd.html) does not have a `new()` method on any platform. I guess calling `borrowed_raw()` was what was is intended, as it is the only applicable method of the struct? I haven't dug into the issue and this failure is several dependencies deep from the crate I actually use, so I might be very wrong in that assumption.

**Comment by taiki-e** [comment]
Fixed in v2.4.0. Thanks for the report!
