### ISSUE TITLE
Compile failed on windows machine

### ISSUE THREAD

**Issue by TheWaWaR** [smol-rs/polling#49]
* The crate version: `polling v2.5.0`
* The rustc version: `1.61.0`

The github action setup:
```yaml
    - if: matrix.os == 'windows-2019'
      name: Windows Dependencies
      run: |
        iwr -useb get.scoop.sh -outfile 'install-scoop.ps1'
        .\install-scoop.ps1 -RunAsAdmin
        echo "LIBCLANG_PATH=$($HOME)/scoop/apps/llvm/current/bin" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
        echo "$env:USERPROFILE\scoop\shims" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
        scoop install llvm yasm
```

The error message:
```
error[E0432]: unresolved import `std::ffi::c_int`
 --> C:\Users\runneradmin\.cargo\registry\src\github.com-1ecc6299db9ec823\polling-2.5.0\src\wepoll.rs:4:5
  |
4 | use std::ffi::c_int;
  |     ^^^^^^^^^^^^^^^ no `c_int` in `ffi`

For more information about this error, try `rustc --explain E0432`.
```

**Comment by taiki-e** [comment]
Thanks for the report! It seems we should use [std::os::raw::c_int](https://doc.rust-lang.org/nightly/std/os/raw/type.c_int.html) (added in rust 1.1) instead of [std::ffi::c_int](https://doc.rust-lang.org/nightly/std/ffi/type.c_int.html) (added in rust 1.64).

**Comment by taiki-e** [comment]
Fixed in v2.5.1 (#50).

**Comment by notgull** [comment]
Whoops, my mistake. We may want to test the MSRV on all platforms to prevent this from happening in the future.

**Comment by TheWaWaR** [comment]
> ~Whoops, my mistake. We may want to test the MSRV on all platforms to prevent this from happening in the future.~ It looks like we do? Strange that it didn't catch that.

I guess maybe more careful chose a rustc version in CI would catch the problem :)

**Comment by taiki-e** [comment]
> ~Whoops, my mistake. We may want to test the MSRV on all platforms to prevent this from happening in the future.~ It looks like we do? Strange that it didn't catch that.

As for windows, I added CI for MSRV in #50.

**Comment by notgull** [comment]
> > ~Whoops, my mistake. We may want to test the MSRV on all platforms to prevent this from happening in the future.~ It looks like we do? Strange that it didn't catch that.
> 
> 
> 
> As for windows, I added CI for MSRV in #50.

Oh, that explains it, thanks for taking care of that.
