### ISSUE TITLE
Poller fails to initialize on old Wine

### ISSUE THREAD

**Issue by notgull** [smol-rs/polling#52]
When running this code on Wine (`wine-6.0.3 (Ubuntu 6.0.3~repack-1)`):

```rust
use polling::Poller;

fn main() -> Result<(), Box<dyn std::error::Error>> {
    // Create a poller.
    let poller = Poller::new()?;
    
    Ok(())
}
```

It yields this error:

```
Error: Os { code: 10045, kind: Uncategorized, message: "OS Error 10045 (FormatMessageW() returned error 317)" }
```

Error 10045 is [`WSAEOPNOTSUPP`](https://learn.microsoft.com/en-us/windows/win32/winsock/windows-sockets-error-codes-2?redirectedfrom=MSDN#WSAEOPNOTSUPP). It looks like this crate suffers from tokio-rs/mio#1444 as well.

`mio` dealt with this issue by not supporting Wine at all. However, `libuv` deals with this using an implementation that spawns a thread pool that runs `select` for every registered listener. This strategy is significantly slower than `wepoll` but is better than crashing. I feel that we can go in either direction here.

Potentially related: async-rs/async-std#943

**Comment by notgull** [comment]
With #54 being merged, should we close this issue? If desired, I could probably implement a thread-pool based solution on top of `blocking` and `select` to support older versions of Wine. However, as Debian and Ubuntu eventually migrate to newer versions of Wine that support Wepoll, that backend would eventually become obsolete. It may just be in our best interest to explicitly not support older Wines.

**Comment by taiki-e** [comment]
Yeah, given that it works with the latest wine and that it is relatively easy to install the latest wine from winehq, I think it is not very worth it to implement a new backend for old wine support. (The situation is different from libuv, which added fallback before wine supported them.)
