### ISSUE TITLE
Release a new patch version?

### ISSUE THREAD

**Issue by wesleywiser** [smol-rs/polling#57]
Dear maintainers,

Would you consider releasing a new patch version that includes #55? I'm working on measuring the impact moving the Rust musl targets to musl 1.2 will have and `polling` is one of the last major crates that doesn't yet have a compatible release. The only other changes since `polling@2.5.1` are 00e7eefc4d08d4d343288a2d95f5c613b435cd33 and 0b455490975d506f92978b0eb850c2e1f3066737 which seem to be semver compatible with `2.5`. 

Thanks!

**Comment by taiki-e** [comment]
Published 2.5.2.
