### ISSUE TITLE
kqueue `modify` handling of events looks weird

### ISSUE THREAD

**Issue by zseri** [smol-rs/polling#64]
This code segment
https://github.com/smol-rs/polling/blob/bc56d1fb380aec713473049b130c28e2835c3a9f/src/kqueue.rs#L101-L124
looks incredibly weird, because it seems that it should be able to basically drop arbitrary oneshot events which occured, as any "non-error" events don't get handled there at all. I would be in favor of not doing any event handling there and just pass an empty eventlist instead to prevent that, handling errors at the next `wait` instead, which imo would be much cleaner (and won't exhibit such race conditions).

**Comment by notgull** [comment]
This might be the bug I'm running headlong into in #59.

**Comment by zseri** [comment]
@notgull I don't think it's the bug you're running into, because I think this should only affect multi-threaded stuff, and the ordering in the test you used didn't use any interleaving or such that could explain that.

**Comment by notgull** [comment]
Looking at `mio`, it looks like it uses [`EV_RECEIPT`](https://github.com/tokio-rs/mio/blob/533c040fd2a2484123d23878c22bdb0acc7436af/src/sys/unix/selector/kqueue.rs#L121) to ensure that the internal buffer is always filled up with receipt events. Using that might fix this issue.
