### ISSUE TITLE
Null pointer dereference in patched wepoll code

### ISSUE THREAD

**Issue by notgull** [smol-rs/polling#85]
See piscisaureus/wepoll#32. It looks like the patched wepoll code has a null pointer dereference for when the poller is notified.

**Comment by notgull** [comment]
From a cursory glance, this issue probably comes from using the distribution `wepoll` with the patched version that the `polling` crate uses. `polling` patches `wepoll` so that a null completion packet can be used to wake up an ongoing poll operation, which is necessary for futures to be able to run themselves. If the distribution `wepoll` is overriding the patched `wepoll`, this means that a null packet sent by `polling` will cause a segmentation fault.

I've opened this here because we're planning on moving away from `wepoll` anyhow, see #22 and #76 (although I'm currently working on an alternative PR that should be easier to debug).

**Comment by taiki-e** [comment]
Um, did the distributor disable wepoll-ffi because of symbol conflicts with the original wepoll?

**Comment by notgull** [comment]
The issue comes down to this:

- A program compiles in `polling`. `polling` brings in a modified version of `wepoll` that's programmed to handle null `OVERLAPPED` wake-up's.
- The program also links `libzmq` statically. `libzmq` embeds the unpatched version of `wepoll`, without support for null `OVERLAPPED` wakeups.
- There are two versions of `wepoll` being compiled into the program. The linker chooses the distribution `wepoll`, without null wakeups support.
- During runtime, `polling‘ uses a null `OVERLAPPED` wakeup to notify `wepoll`. However, the current version of `wepoll` does not expect a null `OVERLAPPED`. It reads from the null pointer and causes a segfault.

A fix for this could be renaming all of the `wepoll` functions so that they are unique and won't conflict with distribution `wepoll` symbols. However, I'd rather spend my time and energy getting #88 working.

**Comment by taiki-e** [comment]
Thanks for the explanation! I agree that removing the dependency on C is the best solution here.

> There are two versions of wepoll being compiled into the program. The linker chooses the distribution wepoll, without null wakeups support.

It is unfortunate that the linker does not report an error in this case.
