### ISSUE TITLE
Support no_std mode

### ISSUE THREAD

**Issue by notgull** [smol-rs/polling#87]
The backend that `polling` uses right now, `libc`, and the backend we intend to use in the future, `rustix`, both support `no_std` mode. It would be nice for #86 to be able to support `no_std`, if only so that the entire Rust standard library isn't bunded into the library.

This would be a breaking change, since we currently use `io::Error` in the public API.

**Comment by taiki-e** [comment]
Given that our code uses std-specific items such as Mutex, I'm not sure if this is actually possible or reasonable.

**Comment by notgull** [comment]
Ah, yeah, I just noticed that. Closing this issue.
