### ISSUE TITLE
Allow mode combining when asking for polling with mode.

### ISSUE THREAD

**Issue by kchibisov** [smol-rs/polling#94]
With at least epoll, `EPOLLONESHOT` could be used on its own(meaning level triggered) or with `Edge`. Right though, you can only do oneshot level triggering, because it simply passed plain oneshot.

**Comment by kchibisov** [comment]
Also, given that oneshot alters behavior of level, could simply add `OneshotEdge` variant, not sure about other platforms though, maybe some have a special one shot meaning.

**Comment by notgull** [comment]
> Also, given that oneshot alters behavior of level, could simply add `OneshotEdge` variant, not sure about other platforms though, maybe some have a special one shot meaning.

This would probably be the best option, as this wouldn't be a breaking change. It would also only work on `epoll` and maybe `kqueue`... but those are the only platforms that support edge triggered I/O anyways, so it wouldn't be too big of a deal.
